version: "3.8"

services:

  db:
    image: postgis/postgis:13-3.1-alpine
    environment:
      POSTGRES_PASSWORD: datacube-test
      POSTGRES_USER: datacube-test
      POSTGRES_DB: datacube-test
      PGDATA: /var/lib/postrgresql/test-data/pgdata
    volumes:
      - type: volume
        source: db-data
        target: /var/lib/postrgresql/test-data
    ports:
      - target: 5432
        published: 7432

volumes:
  db-data: